"""Asynchronous Python client for the Fressnapf Tracker GPS API."""

from .exceptions import (
    FressnapfTrackerError,
    FressnapfTrackerConnectionError,
    FressnapfTrackerAuthenticationError,
    FressnapfTrackerInvalidPhoneNumberError,
    FressnapfTrackerInvalidTokenError,
    FressnapfTrackerInvalidDeviceTokenError,
    FressnapfTrackerInvalidSerialNumberError,
    FressnapfTrackerInvalidTrackerResponseError,
)
from .fressnapftracker import ApiClient, AuthClient
from .models import (
    AdditionalParameters,
    Device,
    MagicLinkResponse,
    MagicLinkUserToken,
    Position,
    TrackerFeatures,
    TrackerSettings,
    LedBrightness,
    DeepSleep,
    EnergySaving,
    LedActivatable,
    ServiceBooking,
    Tracker,
    TrackerUser,
    UserToken,
    PhoneVerificationResponse,
    SmsCodeResponse,
)

__all__ = [
    "ApiClient",
    "AuthClient",
    "FressnapfTrackerError",
    "FressnapfTrackerConnectionError",
    "FressnapfTrackerAuthenticationError",
    "FressnapfTrackerInvalidPhoneNumberError",
    "FressnapfTrackerInvalidTokenError",
    "FressnapfTrackerInvalidDeviceTokenError",
    "FressnapfTrackerInvalidSerialNumberError",
    "FressnapfTrackerInvalidTrackerResponseError",
    "AdditionalParameters",
    "Device",
    "MagicLinkResponse",
    "MagicLinkUserToken",
    "Position",
    "TrackerFeatures",
    "TrackerSettings",
    "LedBrightness",
    "DeepSleep",
    "EnergySaving",
    "LedActivatable",
    "ServiceBooking",
    "Tracker",
    "TrackerUser",
    "UserToken",
    "PhoneVerificationResponse",
    "SmsCodeResponse",
]
